[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "campaignai-backend"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
	"agno",
	"aiohappyeyeballs",
	"aiohttp",
	"aiosignal",
	"annotated-types",
	"anyio",
	"attrs",
	"beautifulsoup4",
	"cachetools",
	"certifi",
	"charset-normalizer",
	"click",
	"colorama",
	"distro",
	"docstring_parser",
	"exa-py",
	"fastapi",
	"firecrawl",
	"frozenlist",
	"google-api-python-client",
	"git-filter-repo",
	"gitdb",
	"GitPython",
	"google-auth",
	"google-genai",
	"ddgs",
	"groq",
	"h11",
	"httpcore",
	"httpx",
	"idna",
	"jiter",
	"markdown-it-py",
	"mdurl",
	"multidict",
	"nest-asyncio",
	"openai",
	"packaging",
	"propcache",
	"pyasn1",
	"pyasn1_modules",
	"pycountry",
	"pydantic",
	"pydantic-settings",
	"pydantic_core",
	"Pygments",
	"python-dotenv",
	"python-multipart",
	"PyYAML",
	"requests",
	"rich",
	"rsa",
	"sendgrid",
	"shellingham",
	"smmap",
	"sniffio",
	"soupsieve",
	"starlette",
	"tenacity",
	"tqdm",
	"typer",
	"typing-inspection",
	"typing_extensions",
	"urllib3",
	"uvicorn",
	"websockets",
	"yarl",
]

[tool.vercel]
entrypoint = "fastapi_market_agent:app"